apiVersion: v2
name: sloboda-stack
description: A Helm chart for Sloboda infrastructure stack
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: m1kkY8
    email: 5rovicmilan89@gmail.com
